//------------------------------------------------------------------------------
// File: constants.h
// Desc: Global constants
//
// Created: 14 September 2005 13:22:28
//
// (c)2005 Neil Wakefield, Lionhead Studios Ltd
//------------------------------------------------------------------------------


#ifndef INCLUSIONGUARD_CONSTANTS_H
#define INCLUSIONGUARD_CONSTANTS_H


//------------------------------------------------------------------------------
// Constants:
//------------------------------------------------------------------------------
const static WCHAR* const	PT_WINDOW_TITLE = L"Prototype";
const static unsigned int	PT_SCREEN_HEIGHT = 900;	//note - width is autogenerated from world aspect ratio

const static char* const	PT_FONT_NAME = "Digital Dream Fat";
const static char* const	PT_FONT_FILE = "assets/fonts/DigitaldreamFat.ttf";
const unsigned int			PT_FONT_SIZE = 72;
const static float			PT_FONT_COLOUR_AMBIENT[4] = { 0.4f, 0.8f, 0.4f, 0.5f };
const static float			PT_FONT_COLOUR_DIFFUSE[4] = { 0.5f, 1.0f, 0.5f, 1.0f };
const static float			PT_FONT_SPIN_RATE = 0.002f;

const static float			PT_WORLD_WIDTH = 400.0f;
const static float			PT_WORLD_HEIGHT = 600.0f;

const static unsigned int	PT_WORLD_STARFIELD_MIN_SPEED = 10;
const static unsigned int	PT_WORLD_STARFIELD_MAX_SPEED = 20;
const static unsigned int	PT_WORLD_STARFIELD_LARGE_SPEED = 17;
const static unsigned int	PT_WORLD_STARFIELD_COLOUR = 0xFF88FF88;

const static float			PT_PP_GAUSSIAN_AMOUNT = 6.0f;

const static float			PT_GUI_WIDTH = 50.0f;

const static unsigned int	PT_GUI_SCORE_COLUMNS = 12;
const static unsigned int	PT_GUI_SCORE_MAX_NAME = 3;
const static unsigned int	PT_GUI_SCORE_NUM_ENTRIES = 10;

const static float			PT_GUI_COLOUR_HEALTH_FG[4] = { 0.1f, 0.3f, 0.1f, 1.0f };
const static float			PT_GUI_COLOUR_HEALTH_BG[4] = { 0.0f, 0.1f, 0.0f, 0.5f };
const static float			PT_GUI_COLOUR_HEALTH_AMBIENT[4] = { 0.1f, 0.1f, 0.1f, 0.2f };
const static float			PT_GUI_COLOUR_LINE_AMBIENT[4] = { 0.2f, 0.3f, 0.2f, 1.0f };

const static float			PT_CAMERA_DEPTH = 20.0f;

const static unsigned int	PT_GAME_TICK_INTERVAL_MS = 100;

const static unsigned int	PT_OBJECT_FLASH_RATE = 4;

const static unsigned int	PT_PLAYER_LIVES = 3;
const static unsigned int	PT_PLAYER_SHIP = 0;
const static unsigned int	PT_PLAYER_AMMO_1 = 1;

const static float			PT_PHYSICS_AIR_RESISTANCE = 0.3f;
const static float			PT_PHYSICS_VELOCITY_CUTOFF = 50.0f;
const static float			PT_PHYSICS_ROLL_MAX = 0.8f;
const static float			PT_PHYSICS_ROLL_RATE = 0.2f;

#endif //INCLUSIONGUARD_CONSTANTS_H
